#!/bin/bash
# This hook is executed each time a charm is upgraded after the new charm
# contents have been unpacked
# Best practice suggests you execute the hooks/install and
# hooks/config-changed to ensure all updates are processed
#apt-get update
#apt-get install --force-yes -y nexus-1000v-vem-dkms
#apt-get install --force-yes -y nexus-1000v-vem
apt-mark unhold openvswitch-common openvswitch-switch
cp data.yaml.orig data.yaml
hooks/install
hooks/config-changed
